version: '3.8'

services:
  inboxpilot:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MICROSOFT_TENANT_ID=${MICROSOFT_TENANT_ID}
      - MICROSOFT_CLIENT_ID=${MICROSOFT_CLIENT_ID}
      - MICROSOFT_CLIENT_SECRET=${MICROSOFT_CLIENT_SECRET}
      - WEBHOOK_BASE_URL=${WEBHOOK_BASE_URL}
      - WEBHOOK_VALIDATION_TOKEN=${WEBHOOK_VALIDATION_TOKEN}
      - LANGFLOW_WEBHOOK_URL=${LANGFLOW_WEBHOOK_URL}
      - WEBHOOK_HOST=0.0.0.0
      - WEBHOOK_PORT=8000
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add Langflow service
  langflow:
    image: langflowai/langflow:latest
    ports:
      - "7860:7860"
    environment:
      - LANGFLOW_DATABASE_URL=sqlite:///./langflow.db
    volumes:
      - langflow_data:/app/langflow
    restart: unless-stopped

volumes:
  langflow_data: 